-- Adds is_internal + is_bot flags to provider_events so the admin analytics
-- dashboard can exclude traffic generated by staff sessions and known
-- crawlers/prerender services. Both columns default to false; the
-- `track-provider-event` edge function sets them per request based on the
-- caller's Authorization JWT (admin role check) and User-Agent header (bot
-- pattern match).
--
-- Why this matters: pre-2026-05-21 every Googlebot/Bingbot/prerender hit
-- and every admin browsing their own facilities inflated the visitor count
-- shown on /admin/analytics. GA4 silently filters bots via Google's
-- automatic bot list (and we exclude staff via the new traffic_type user
-- property), so admin counts ran higher than GA. With these flags the two
-- streams can be reconciled at query time.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='provider_events' AND column_name='is_internal'
  ) THEN
    ALTER TABLE public.provider_events ADD COLUMN is_internal boolean NOT NULL DEFAULT false;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='provider_events' AND column_name='is_bot'
  ) THEN
    ALTER TABLE public.provider_events ADD COLUMN is_bot boolean NOT NULL DEFAULT false;
  END IF;
END $$;

-- Index to keep the "exclude internal+bot" filter cheap on the dashboard's
-- ranged scans (event_type IN (...) AND created_at >= ... AND NOT is_internal
-- AND NOT is_bot). Partial index keeps the storage small — almost all rows
-- are external+human, so we only index the predicate that matters.
CREATE INDEX IF NOT EXISTS idx_provider_events_external_human
  ON public.provider_events (event_type, created_at DESC)
  WHERE is_internal = false AND is_bot = false;

COMMENT ON COLUMN public.provider_events.is_internal IS
  'True when the event was emitted by a logged-in staff user (admin, super_admin, or manager). The /admin/analytics dashboard excludes these from "visitor" counts so the metric reflects external traffic only.';
COMMENT ON COLUMN public.provider_events.is_bot IS
  'True when the User-Agent header on the originating request matches a known bot/crawler/prerender pattern. The /admin/analytics dashboard excludes these so counts reconcile with GA4 (which applies its own automatic bot filter).';
