-- Add any missing fields to concierge_inquiries for Phase 1 intake
ALTER TABLE public.concierge_inquiries 
ADD COLUMN IF NOT EXISTS preferred_language text DEFAULT 'english',
ADD COLUMN IF NOT EXISTS relationship_to_seeker text,
ADD COLUMN IF NOT EXISTS substance_use_frequency text,
ADD COLUMN IF NOT EXISTS substance_use_duration text,
ADD COLUMN IF NOT EXISTS detox_needed text,
ADD COLUMN IF NOT EXISTS current_medications text,
ADD COLUMN IF NOT EXISTS suicide_history text,
ADD COLUMN IF NOT EXISTS preferred_environment text,
ADD COLUMN IF NOT EXISTS faith_based_preference text,
ADD COLUMN IF NOT EXISTS holistic_interest boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS amenity_preferences jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS insurance_member_id text,
ADD COLUMN IF NOT EXISTS insurance_group_number text,
ADD COLUMN IF NOT EXISTS employer_name text,
ADD COLUMN IF NOT EXISTS benefits_verified boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS scholarship_interest boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS alternative_contact_name text,
ADD COLUMN IF NOT EXISTS alternative_contact_phone text,
ADD COLUMN IF NOT EXISTS emergency_contact_name text,
ADD COLUMN IF NOT EXISTS emergency_contact_phone text,
ADD COLUMN IF NOT EXISTS referral_source text,
ADD COLUMN IF NOT EXISTS hipaa_consent boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS gender text,
ADD COLUMN IF NOT EXISTS mobility_needs text,
ADD COLUMN IF NOT EXISTS current_living_situation text;